version: '3.8'

services:
  cms-mysql:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - cms-mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  cms-mysql-data:
