version: '3.8'

services:
  cms-postgres:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - cms-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  cms-postgres-data: